### ISSUE TITLE
Update docs, test payum/payum, composer add bcmath require

### ISSUE THREAD

**Issue by alipek** [alipek/payum-dotpay#1]
Add tip configuration for symfony 3
```yml
  pixers.payum.dotpay.dotpay_gateway_factory:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments: [Pixers\Payum\Dotpay\DotpayGatewayFactory]
    tags:
      - { name: 'payum.gateway_factory_builder', factory: 'dotpay' }
```
